[project]
name = "cave-generator"
version = "0.1.0"
description = ""
authors = [
    {name = "LosEvons",email = "emil.malk@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12.3, <3.14.1 || >3.14.1" # networkx doesn't work with 3.14.1
dependencies = [
    "tcod (>=20.1.0,<21.0.0)",
    "numpy (>=2.5.1,<3.0.0)",
    "scipy (>=1.18.0,<2.0.0)",
    "sympy (>=1.14.0,<2.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "networkx (>=3.6.1,<4.0.0)"
]

[project.scripts]
cave-generator = "main:cli"

[tool.poetry]
packages = [
    { include = "main.py" },
    { include = "generate_rooms.py" },
    { include = "matrix2d.py" },
    { include = "utils.py" },
]


[tool.poetry.group.dev.dependencies]
pytest-cov = "^7.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "--cov=. --cov-report=term-missing"

[tool.coverage.run]
omit = ["main.py", "tests/*", "utils.py"]